#Create custom yolo model
model:
  arch: YOLOLiteMS_CPU
  backbone: cs3darknet_focus_s
  depth_multiple: 0.90
  width_multiple: 0.75
  fpn_channels: 256
  head_depth: 2
















